### ISSUE TITLE
Is It Possible To Get This to Work With MongoDB's ObjectId Type

### ISSUE THREAD

**Issue by bbrandt** [autoguru-au/hotchocolate-polymorphic-ids#7]
Thanks for the excellent library!  Polymorphic ids is such a great idea!

Is it possible to get this to work with MongoDB's [MongoDB.Bson.ObjectId](https://mongodb.github.io/mongo-csharp-driver/2.6/apidocs/html/T_MongoDB_Bson_ObjectId.htm) type? Or, is it even a good idea to use ObjectId as an ID field?

```csharp
    [NodeEx]
    public class SomeEntity
    {
        /// <summary>
        /// Id that uniquely identifies this entity
        /// </summary>
        [ID]
        public ObjectId Id { get; set; }


        [Required]
        public string? Name { get; set; }

        public string? Description { get; set; }

        public static async Task<SomeEntity> Get([ID] ObjectId id,
            [Service] SomeEntityDataLoader service)
        {
            var node= await service.LoadAsync(id);
            return node;
        }
    }
```

**Comment by bbrandt** [comment]
It looks like a code change would be necessary for custom types.  For now I have switched to representing my ObjectId as a string to get polymorphic id's working:
```csharp
        [ID]
        [BsonRepresentation(BsonType.ObjectId)]
        public string Id { get; set; } = string.Empty;
```

**Comment by benmccallum** [comment]
Sorry @bbrandt , happy to leave this open and have a closer look when I get time. It's been a while since I've been in MongoDB land. What type do you represent mongo ids as usually @pascalsenn?

**Comment by bbrandt** [comment]
Thanks for the reply.

I do not need it left open as we are early in our project with HC and Mongo, making it cheap to do, and switching over to string is working great for us.
